export type Routes = {
  Home: undefined;
  HelloTriangle: undefined;
  HelloTriangleMSAA: undefined;
  Cube: undefined;
  InstancedCube: undefined;
  TexturedCube: undefined;
  FractalCube: undefined;
  Cubemap: undefined;
  SamplerParameters: undefined;
  RenderBundles: undefined;
  OcclusionQuery: undefined;
  ComputeBoids: undefined;
  ABuffer: undefined;
  Particles: undefined;
  ShadowMapping: undefined;
  DeferedRendering: undefined;
  ReversedZ: undefined;
  Wireframe: undefined;
  Resize: undefined;
  Tests: undefined;
};
