
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook::react {

class WebGPUViewProps final : public ViewProps {
 public:
  WebGPUViewProps() = default;
  WebGPUViewProps(const PropsParserContext& context, const WebGPUViewProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  int contextId{0};
};

} // namespace facebook::react
