// Template for the generated packages/webgpu/Package.swift.
// Kept in its own module so generate-package-swift.ts stays focused on
// fetching the release metadata.
//
// The manifest mirrors @shopify/react-native-skia's packages/skia/Package.swift
// (same integration model, same relative paths, same platform floor, same
// defines). Keep the two aligned when changing either.

export type WebGPUDawnBinaryTarget =
  | { kind: "remote"; url: string; checksum: string }
  | { kind: "local"; path: string };

export interface PackageSwiftInputs {
  target: WebGPUDawnBinaryTarget;
  // Dawn release tag, e.g. "dawn-chrome-m154". Same string that
  // @shopify/react-native-skia's Graphite installer records in
  // libs/.dawn-version, which is what the manifest compares against.
  dawnReleaseTag: string;
}

// Must match `spm.name` in react-native.config.js: React Native's autolinker
// looks the product up by that name, and it is the package identity too.
export const SWIFT_PACKAGE_NAME = "ReactNativeWebGPU";

const renderBinaryTarget = (target: WebGPUDawnBinaryTarget) =>
  target.kind === "remote"
    ? `.binaryTarget(
      name: "WebGPUDawn",
      url: "${target.url}",
      checksum: "${target.checksum}"
    )`
    : `.binaryTarget(
      name: "WebGPUDawn",
      path: "${target.path}"
    )`;

export const renderPackageSwift = ({
  target,
  dawnReleaseTag,
}: PackageSwiftInputs) => `// swift-tools-version: 6.0
// Generated by scripts/generate-package-swift.ts — do not edit by hand.
// Re-run that script after a new Dawn release to update the URL/checksum below.
//
// SwiftPM manifest for react-native-webgpu. iOS only.
// Additive: the CocoaPods podspec remains the supported default.
//
// React Native 0.87+ references a library that ships its own Package.swift
// through a symlink at <app>/ios/build/generated/autolinking/libs/<name>, and
// resolves the relative paths below against that symlink. They are the same
// for every standard app, because the symlink location is. Earlier React
// Native releases have no SwiftPM autolinking: keep CocoaPods there.

import Foundation
import PackageDescription

// Absolute location of this package. Xcode passes the autolinking symlink as
// the package directory, so resolve it before deriving sibling paths.
let packageRoot = URL(fileURLWithPath: Context.packageDirectory)
  .resolvingSymlinksInPath().path
let sibling = { (relative: String) -> String in
  URL(fileURLWithPath: "\\(packageRoot)/\\(relative)").standardized.path
}

// Skia Graphite and WebGPU must link the exact same Dawn, or the pair links
// fine and crashes at runtime. react-native-skia's podspec enforces this at
// \`pod install\` time by comparing its libs/.dawn-version against this
// package's \`dawn\` field. A Swift package has no install hook, so the same
// check runs here, at manifest evaluation. SwiftPM caches evaluations, so
// after changing either package's Dawn version reset the package caches
// (File > Packages > Reset Package Caches) if this does not re-run.
let dawnReleaseTag = "${dawnReleaseTag}"
let skiaCandidates = [
  sibling("../@shopify/react-native-skia"), // consumer: sibling in node_modules
  sibling("../../node_modules/@shopify/react-native-skia"), // this monorepo
]
for skia in skiaCandidates {
  // Only Graphite builds of react-native-skia write this marker (Ganesh
  // builds do not link Dawn and impose no constraint).
  guard let data = FileManager.default.contents(atPath: "\\(skia)/libs/.dawn-version"),
    let skiaDawn = String(data: data, encoding: .utf8)?
      .trimmingCharacters(in: .whitespacesAndNewlines)
  else { continue }
  if skiaDawn != dawnReleaseTag {
    fatalError(
      """
      react-native-webgpu: Dawn version mismatch. This package links \\(dawnReleaseTag) \\
      but the @shopify/react-native-skia Graphite build at \\(skia) links \\(skiaDawn). \\
      Align the two packages so the app contains exactly one Dawn.
      """)
  }
  break
}

// Unlike a native Xcode target, SwiftPM doesn't generate an implicit
// per-target header map, so quoted includes only resolve within the
// including file's own directory. The sources use bare cross-directory
// includes (e.g. apple/WebGPUModule.h includes "RNWebGPUManager.h" from
// cpp/rnwgpu), so every directory that's the target of one of those bare
// includes has to be listed explicitly here.
let internalHeaderDirs = [
  "apple",
  // "cpp" itself resolves the "webgpu/..." and "dawn/..." namespaced
  // includes. Those two directories are only present locally when built via
  // \`yarn install-dawn\` (without the xcframework's embedded headers); a
  // remote binaryTarget's xcframework embeds them instead (see
  // build-dawn.yml's \`-headers\` flag), so "cpp" not containing them there
  // is fine — the xcframework's own headers cover it.
  "cpp",
  "cpp/jsi",
  "cpp/rnwgpu",
  "cpp/rnwgpu/api",
  "cpp/rnwgpu/api/descriptors",
  "cpp/rnwgpu/async",
]

let package = Package(
  name: "${SWIFT_PACKAGE_NAME}",
  // SwiftPM refuses to link a product whose floor is above the depending
  // target's. React Native's generated Autolinked aggregate hardcodes iOS 15.0
  // (react-native#58379 derives it from the app instead), so this must not
  // exceed 15.0 — a lower floor is always accepted.
  platforms: [.iOS(.v15)],
  products: [
    // Autolinking looks this name up verbatim; react-native.config.js pins it.
    .library(name: "${SWIFT_PACKAGE_NAME}", targets: ["${SWIFT_PACKAGE_NAME}"])
  ],
  dependencies: [
    .package(name: "React-GeneratedCode", path: "../../../ios"),
    .package(name: "ReactNative", path: "../../../../xcframeworks"),
  ],
  targets: [
    // Dawn's compiled WebGPU implementation. The xcframework embeds the
    // \`webgpu/\` and \`dawn/\` C headers per-slice (built via \`-headers\` in
    // build-dawn.yml), so SPM exposes them to dependents automatically.
    ${renderBinaryTarget(target)},
    .target(
      name: "${SWIFT_PACKAGE_NAME}",
      dependencies: [
        .product(name: "ReactHeaders", package: "ReactNative"),
        .product(name: "ReactNativeHeaders", package: "ReactNative"),
        .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
        // RNWgpuViewSpec, generated by the app's codegen run.
        .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
        "WebGPUDawn",
      ],
      // apple/ and cpp/ have no common ancestor below the package root, and
      // .headerSearchPath cannot escape the target path.
      path: ".",
      // Explicit, so SwiftPM never walks node_modules, lib, android, or the
      // headers-only cpp/webgpu and cpp/dawn trees.
      sources: ["apple", "cpp/jsi", "cpp/rnwgpu"],
      // SwiftPM requires a public headers directory inside the target and
      // defaults to "include", which this package does not have.
      publicHeadersPath: "apple",
      cxxSettings: internalHeaderDirs.map { CXXSetting.headerSearchPath($0) } + [
        // CocoaPods forces both project-wide; the SwiftPM path defines neither.
        // React Native's headers gate on them, and the prebuilt React.framework
        // was built with both, so the module must see the same declarations.
        .define("RCT_NEW_ARCH_ENABLED", to: "1"),
        .define("RCT_REMOVE_LEGACY_ARCH", to: "1"),

        // React's prebuilt C++ ABI is NDEBUG-gated (DebugStringConvertible's
        // vtable and ShadowNode layout diverge). Omitting either breaks the
        // Release link.
        .define("DEBUG", .when(configuration: .debug)),
        .define("NDEBUG", .when(configuration: .release)),
      ],
      linkerSettings: [
        // VideoPlayer uses AVFoundation / CoreMedia, shared-texture surfaces
        // use CoreVideo (CVPixelBuffer), and ImageIO provides CGImageSource,
        // the image decoder behind createImageBitmap.
        .linkedFramework("AVFoundation"),
        .linkedFramework("CoreMedia"),
        .linkedFramework("CoreVideo"),
        .linkedFramework("ImageIO"),
      ]
    ),
  ],
  // React Native's headers need C++20.
  cxxLanguageStandard: .cxx20
)
`;
