// Template for the generated packages/webgpu/Package.swift.
// Kept in its own module so generate-package-swift.ts stays focused on
// fetching the release metadata.

export type WebGPUDawnBinaryTarget =
  | { kind: "remote"; url: string; checksum: string }
  | { kind: "local"; path: string };

export interface PackageSwiftInputs {
  target: WebGPUDawnBinaryTarget;
  // Dawn release tag, e.g. "dawn-chrome-m154". Same string that
  // @shopify/react-native-skia's Graphite installer records in
  // libs/.dawn-version, which is what the manifest compares against.
  dawnReleaseTag: string;
}

const renderBinaryTarget = (target: WebGPUDawnBinaryTarget) =>
  target.kind === "remote"
    ? `.binaryTarget(
      name: "WebGPUDawn",
      url: "${target.url}",
      checksum: "${target.checksum}"
    )`
    : `.binaryTarget(
      name: "WebGPUDawn",
      path: "${target.path}"
    )`;

export const renderPackageSwift = ({
  target,
  dawnReleaseTag,
}: PackageSwiftInputs) => `// swift-tools-version: 5.9
// Generated by scripts/generate-package-swift.ts — do not edit by hand.
// Re-run that script after a new Dawn release to update the URL/checksum below.
import Foundation
import PackageDescription

// Integration model: this manifest self-detects which of two consumers it is
// evaluated for, and builds different target wiring for each.
//
// 1. React Native 0.81-0.86: a local Swift package added next to a CocoaPods
//    install (export RNWGPU_USE_SPM=1 for \`pod install\`, keep running
//    \`pod install\` for everything else). React Native's own headers and the
//    RNWgpuViewSpec codegen output only exist inside the consuming app's
//    CocoaPods install, so the header search paths below point into that Pods
//    directory. They can only be expressed as \`unsafeFlags\`, and SwiftPM
//    rejects unsafeFlags in anything but a path dependency, so in this mode
//    the package can only be consumed locally, never by URL and version.
//
// 2. React Native 0.87+ native SwiftPM autolinking: a dependency shipping its
//    own Package.swift (this one, with react-native.config.js pinning its
//    \`spm.name\`) is picked up as "self-managed" and referenced directly, with
//    no CocoaPods involved at all. Autolinking references it through a
//    symlink at <app>/ios/build/generated/autolinking/libs/react-native-webgpu,
//    and SwiftPM resolves this manifest's relative paths against that symlink
//    rather than against this package's real location - the same mechanism
//    Shopify/react-native-skia's Package.swift documents and uses (PR #4043).
//    Because the symlink location is the same for every standard app, the two
//    React Native package paths below are constant. In this mode React
//    Native's headers and the app's generated codegen output arrive as
//    typed SwiftPM products (ReactHeaders, ReactNativeHeaders,
//    ReactNativeDependenciesHeaders from the generated ReactNative package,
//    ReactAppHeaders from the generated React-GeneratedCode package) instead
//    of raw header search paths, so none of the CocoaPods-derived
//    unsafeFlags apply.
//
// Which mode applies is detected once below, from whether the native
// autolinking packages exist at their fixed relative location - the same
// existence-probing pattern the CocoaPods podsRoot lookup already used.

// Absolute location of this package. Xcode may hand over a symlink (React
// Native 0.87's autolinker does), so resolve it before deriving sibling paths.
let packageRoot = URL(fileURLWithPath: Context.packageDirectory)
  .resolvingSymlinksInPath().path
let sibling = { (relative: String) -> String in
  URL(fileURLWithPath: "\\(packageRoot)/\\(relative)").standardized.path
}

// The literal strings passed to \`.package(path:)\` below (further down) are
// NOT the same paths this probe checks. SwiftPM resolves a dependency's
// relative \`path:\` against wherever Xcode's own project graph says the
// manifest lives - the symlink itself under a real Xcode build
// (react-native-skia#4043 verified this: "resolves the manifest's relative
// paths against that symlink rather than against packages/skia") - but
// \`Context.packageDirectory\`, which manifest script code actually gets
// handed, is already realpath()'d and never exposes that symlink (verified:
// even \`swift package --package-path <symlink> dump-package\` reports the
// resolved directory, not the symlink). So this probe can't check the
// symlink-relative location the eventual \`.package(path:)\` call will use -
// it instead checks the same real, non-symlinked location \`packageRoot\`
// already reaches for the CocoaPods candidates below, just two levels
// shallower (the app root, rather than its Pods/ or xcframeworks/ child).
let nativeAutolinkingAppRootCandidates = [
  sibling("../.."), // consumer: <app>/node_modules/react-native-webgpu
  sibling("../../apps/spm-example"), // this monorepo
]
let nativeAutolinkingAppRoot = nativeAutolinkingAppRootCandidates.first {
  FileManager.default.fileExists(atPath: "\\($0)/ios/build/generated/ios/Package.swift")
    && FileManager.default.fileExists(atPath: "\\($0)/ios/build/xcframeworks/Package.swift")
}
let isNativeAutolinked = nativeAutolinkingAppRoot != nil
// Passed to \`.package(path:)\` as literal strings (see the comment above) -
// resolved by SwiftPM itself against the symlinked location react-native.config.js's
// \`spm.name\` pins, not computed from \`packageRoot\`/\`sibling\`. Verified against
// a real \`npx react-native spm scaffold\` run on 0.87.1: the self-managed symlink
// lands at <app>/ios/build/generated/autolinking/libs/react-native-webgpu, and
// React-GeneratedCode / ReactNative sit at <app>/ios/build/generated/ios and
// <app>/ios/build/xcframeworks respectively - three and four levels up from
// there.
let reactGeneratedCodePath = "../../../ios"
let reactNativeCorePath = "../../../../xcframeworks"

// Where the consuming app's Pods live. PODS_ROOT is exported by Xcode.app for
// a real build, but never by plain \`xcodebuild\`, and never while Xcode indexes
// the manifest before a first build. SwiftPM also caches manifest evaluations,
// so an evaluation that ran without it would otherwise be cached with an empty
// include list and surface later as header-not-found errors. Fall back to
// where Pods sit relative to this package for every standard app layout, so
// the result is the same with or without the environment variable.
let podsRootCandidates = [
  sibling("../../ios/Pods"), // consumer: <app>/node_modules/react-native-webgpu
  sibling("../../apps/spm-example/ios/Pods"), // this monorepo
]
let podsRoot =
  ProcessInfo.processInfo.environment["PODS_ROOT"]
  ?? podsRootCandidates.first { FileManager.default.fileExists(atPath: $0) }
  ?? podsRootCandidates[0]

// Skia Graphite and WebGPU must link the exact same Dawn, or the pair links
// fine and crashes at runtime. react-native-skia's podspec enforces this at
// \`pod install\` time by comparing its libs/.dawn-version against this
// package's \`dawn\` field. A Swift package has no install hook, so the same
// check runs here, at manifest evaluation. SwiftPM caches evaluations, so
// after changing either package's Dawn version reset the package caches
// (File > Packages > Reset Package Caches) if this does not re-run.
let dawnReleaseTag = "${dawnReleaseTag}"
let skiaCandidates = [
  sibling("../@shopify/react-native-skia"), // consumer: sibling in node_modules
  sibling("../../node_modules/@shopify/react-native-skia"), // this monorepo
]
for skia in skiaCandidates {
  // Only Graphite builds of react-native-skia write this marker (Ganesh
  // builds do not link Dawn and impose no constraint).
  guard let data = FileManager.default.contents(atPath: "\\(skia)/libs/.dawn-version"),
    let skiaDawn = String(data: data, encoding: .utf8)?
      .trimmingCharacters(in: .whitespacesAndNewlines)
  else { continue }
  if skiaDawn != dawnReleaseTag {
    fatalError(
      """
      react-native-webgpu: Dawn version mismatch. This package links \\(dawnReleaseTag) \\
      but the @shopify/react-native-skia Graphite build at \\(skia) links \\(skiaDawn). \\
      Align the two packages so the app contains exactly one Dawn.
      """)
  }
  break
}

// Static-library Pods layout. With \`use_frameworks!\` CocoaPods keeps headers
// inside each framework instead and none of these paths exist; the podspec
// refuses RNWGPU_USE_SPM in that mode.
let publicHeaders = "\\(podsRoot)/Headers/Public"
let privateHeaders = "\\(podsRoot)/Headers/Private"
let headerSearchPaths = [
  publicHeaders,
  // Yoga's headers are CocoaPods-private (apps aren't meant to use Yoga's
  // C++ API directly), but React-Fabric's view props headers include them
  // transitively.
  "\\(privateHeaders)/Yoga",
  "\\(publicHeaders)/React-Core",
  "\\(publicHeaders)/React-jsi",
  "\\(publicHeaders)/React-callinvoker",
  "\\(publicHeaders)/React-NativeModulesApple",
  "\\(publicHeaders)/React-RCTFabric",
  "\\(publicHeaders)/ReactCodegen",
  "\\(publicHeaders)/RCT-Folly",
  "\\(publicHeaders)/RCTRequired",
  "\\(publicHeaders)/RCTTypeSafety",
  "\\(publicHeaders)/FBLazyVector",
  "\\(publicHeaders)/ReactCommon",
  "\\(publicHeaders)/React-Fabric",
  "\\(publicHeaders)/React-graphics",
  "\\(publicHeaders)/React-utils",
  "\\(publicHeaders)/React-featureflags",
  "\\(publicHeaders)/React-rendererdebug",
  "\\(publicHeaders)/React-debug",
  "\\(publicHeaders)/React-timing",
  "\\(publicHeaders)/React-runtimescheduler",
  "\\(publicHeaders)/React-rendererconsistency",
  "\\(publicHeaders)/React-performancetimeline",
  "\\(publicHeaders)/React-runtimeexecutor",
  "\\(publicHeaders)/React-cxxreact",
  "\\(publicHeaders)/hermes-engine",
  "\\(publicHeaders)/glog",
  "\\(publicHeaders)/DoubleConversion",
  "\\(publicHeaders)/fmt",
  "\\(publicHeaders)/fast_float",
]
// The only unsafe flags left: .headerSearchPath cannot escape the target
// path, and these live in the app's Pods directory.
let cFamilyIncludeFlags = headerSearchPaths.map { "-I\\($0)" }
let follyDefines: [(name: String, value: String?)] = [
  ("FOLLY_NO_CONFIG", nil),
  ("FOLLY_MOBILE", "1"),
  ("FOLLY_USE_LIBCPP", "1"),
  ("FOLLY_CFG_NO_COROUTINES", "1"),
  ("FOLLY_HAVE_CLOCK_GETTIME", "1"),
]

// Unlike a native Xcode target, SwiftPM doesn't generate an implicit
// per-target header map, so quoted includes only resolve within the
// including file's own directory. The sources use bare cross-directory
// includes (e.g. apple/WebGPUModule.h includes "RNWebGPUManager.h" from
// cpp/rnwgpu), so every directory that's the target of one of those bare
// includes has to be listed explicitly here.
let internalHeaderDirs = [
  "apple",
  // "cpp" itself resolves the "webgpu/..." and "dawn/..." namespaced
  // includes. Those two directories are only present locally when built via
  // \`yarn install-dawn\` (without the xcframework's embedded headers); a
  // remote binaryTarget's xcframework embeds them instead (see
  // build-dawn.yml's \`-headers\` flag), so "cpp" not containing them there
  // is fine — the xcframework's own headers cover it.
  "cpp",
  "cpp/jsi",
  "cpp/rnwgpu",
  "cpp/rnwgpu/api",
  "cpp/rnwgpu/api/descriptors",
  "cpp/rnwgpu/async",
]

// Native-autolinking-only package dependencies: the generated packages that
// vend React Native's headers and the app's codegen output as SwiftPM
// products. Left empty under CocoaPods, where these paths don't exist and
// nothing in this manifest references their products.
// Passed as the same literal relative strings used for detection above -
// SwiftPM resolves these itself, lexically, against the manifest's own
// (possibly symlinked) location.
let nativeAutolinkingDependencies: [Package.Dependency] =
  isNativeAutolinked
  ? [
    .package(name: "React-GeneratedCode", path: reactGeneratedCodePath),
    .package(name: "ReactNative", path: reactNativeCorePath),
  ]
  : []

let webgpuDependencies: [Target.Dependency] =
  isNativeAutolinked
  ? [
    "WebGPUDawn",
    .product(name: "ReactHeaders", package: "ReactNative"),
    .product(name: "ReactNativeHeaders", package: "ReactNative"),
    .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
    .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
  ]
  : ["WebGPUDawn"]

let webgpuCSettings: [CSetting] =
  internalHeaderDirs.map { CSetting.headerSearchPath($0) }
  + follyDefines.map { CSetting.define($0.name, to: $0.value) }
  + (isNativeAutolinked ? [] : [.unsafeFlags(cFamilyIncludeFlags)])

let webgpuCxxSettings: [CXXSetting] =
  internalHeaderDirs.map { CXXSetting.headerSearchPath($0) }
  + follyDefines.map { CXXSetting.define($0.name, to: $0.value) }
  + (isNativeAutolinked
    ? [
      // CocoaPods forces both project-wide; native autolinking defines
      // neither. Cheap insurance against a silent -getTurboModule: drop
      // (react-native-skia#4043 hit exactly this) - still verify with a
      // runtime smoke test, not just a clean build, since that failure mode
      // compiles fine and only breaks at runtime.
      .define("RCT_NEW_ARCH_ENABLED", to: "1"),
      .define("RCT_REMOVE_LEGACY_ARCH", to: "1"),
    ]
    : [.unsafeFlags(cFamilyIncludeFlags)])

let package = Package(
  name: "react-native-webgpu",
  platforms: [.iOS("15.1"), .macOS("11.0")],
  products: [
    .library(name: "react-native-webgpu", targets: ["react-native-webgpu"]),
    // Exposes the Dawn binaryTarget as its own product so a sibling package
    // (e.g. a future react-native-skia Graphite SPM manifest) can depend on
    // this package's Dawn build directly instead of vendoring a second copy.
    .library(name: "WebGPUDawn", targets: ["WebGPUDawn"]),
  ],
  dependencies: nativeAutolinkingDependencies,
  targets: [
    // Dawn's compiled WebGPU implementation. The xcframework embeds the
    // \`webgpu/\` and \`dawn/\` C headers per-slice (built via \`-headers\` in
    // build-dawn.yml), so SPM exposes them to dependents automatically.
    ${renderBinaryTarget(target)},
    .target(
      name: "react-native-webgpu",
      dependencies: webgpuDependencies,
      path: ".",
      sources: ["apple", "cpp/jsi", "cpp/rnwgpu"],
      publicHeadersPath: "apple",
      cSettings: webgpuCSettings,
      cxxSettings: webgpuCxxSettings,
      linkerSettings: [
        .linkedFramework("AVFoundation"),
        .linkedFramework("CoreMedia"),
        .linkedFramework("CoreVideo"),
        .linkedFramework("ImageIO"),
      ]
    ),
  ],
  cxxLanguageStandard: .cxx20
)
`;
