// Template for the generated packages/webgpu/Package.swift.
// Kept in its own module so generate-package-swift.ts stays focused on
// fetching the release metadata.

export type WebGPUDawnBinaryTarget =
  | { kind: "remote"; url: string; checksum: string }
  | { kind: "local"; path: string };

const renderBinaryTarget = (target: WebGPUDawnBinaryTarget) =>
  target.kind === "remote"
    ? `.binaryTarget(
      name: "WebGPUDawn",
      url: "${target.url}",
      checksum: "${target.checksum}"
    )`
    : `.binaryTarget(
      name: "WebGPUDawn",
      path: "${target.path}"
    )`;

export const renderPackageSwift = (target: WebGPUDawnBinaryTarget) => `// swift-tools-version: 5.9
// Generated by scripts/generate-package-swift.ts — do not edit by hand.
// Re-run that script after a new Dawn release to update the URL/checksum below.
import Foundation
import PackageDescription

// React Native's CLI has no SPM autolinking for third-party TurboModule/Fabric
// libraries yet, and the RNWgpuViewSpec codegen headers only exist inside the
// consuming app's per-project "ReactCodegen" pod. So this package still leans
// on the host app's CocoaPods install for React Native's own headers: add this
// Package.swift as a local Swift Package dependency in place of the
// react-native-webgpu pod, but keep running \`pod install\` for everything else.
// Xcode/CocoaPods export PODS_ROOT as a real environment variable during an
// actual build (it comes from the Pods-<Target>.xcconfig), so this resolves
// once the consuming app has run \`pod install\`. It's only unset before that,
// or while Xcode is indexing the manifest prior to a first build.
let srcRoot = ProcessInfo.processInfo.environment["SRCROOT"]
let podsRoot =
  ProcessInfo.processInfo.environment["PODS_ROOT"]
  ?? srcRoot.map { "\\($0)/Pods" }
  ?? ""
let publicHeaders = "\\(podsRoot)/Headers/Public"
let privateHeaders = "\\(podsRoot)/Headers/Private"
let headerSearchPaths = [
  publicHeaders,
  // Yoga's headers are CocoaPods-private (apps aren't meant to use Yoga's
  // C++ API directly), but React-Fabric's view props headers include them
  // transitively.
  "\\(privateHeaders)/Yoga",
  "\\(publicHeaders)/React-Core",
  "\\(publicHeaders)/React-jsi",
  "\\(publicHeaders)/React-callinvoker",
  "\\(publicHeaders)/React-NativeModulesApple",
  "\\(publicHeaders)/React-RCTFabric",
  "\\(publicHeaders)/ReactCodegen",
  "\\(publicHeaders)/RCT-Folly",
  "\\(publicHeaders)/RCTRequired",
  "\\(publicHeaders)/RCTTypeSafety",
  "\\(publicHeaders)/FBLazyVector",
  "\\(publicHeaders)/ReactCommon",
  "\\(publicHeaders)/React-Fabric",
  "\\(publicHeaders)/React-graphics",
  "\\(publicHeaders)/React-utils",
  "\\(publicHeaders)/React-featureflags",
  "\\(publicHeaders)/React-rendererdebug",
  "\\(publicHeaders)/React-debug",
  "\\(publicHeaders)/React-timing",
  "\\(publicHeaders)/React-runtimescheduler",
  "\\(publicHeaders)/React-rendererconsistency",
  "\\(publicHeaders)/React-performancetimeline",
  "\\(publicHeaders)/React-runtimeexecutor",
  "\\(publicHeaders)/React-cxxreact",
  "\\(publicHeaders)/hermes-engine",
  "\\(publicHeaders)/glog",
  "\\(publicHeaders)/DoubleConversion",
  "\\(publicHeaders)/fmt",
  "\\(publicHeaders)/fast_float",
]
let cFamilyIncludeFlags = headerSearchPaths.map { "-I\\($0)" }
let follyDefines = [
  "-DFOLLY_NO_CONFIG",
  "-DFOLLY_MOBILE=1",
  "-DFOLLY_USE_LIBCPP=1",
  "-DFOLLY_CFG_NO_COROUTINES=1",
  "-DFOLLY_HAVE_CLOCK_GETTIME=1",
]

// Unlike a native Xcode target, SwiftPM doesn't generate an implicit
// per-target header map, so quoted includes only resolve within the
// including file's own directory. The sources use bare cross-directory
// includes (e.g. apple/WebGPUModule.h includes "RNWebGPUManager.h" from
// cpp/rnwgpu), so every directory that's the target of one of those bare
// includes has to be listed explicitly here.
let internalHeaderDirs = [
  "apple",
  // "cpp" itself resolves the "webgpu/..." and "dawn/..." namespaced
  // includes. Those two directories are only present locally when built via
  // \`yarn install-dawn\` (without the xcframework's embedded headers); a
  // remote binaryTarget's xcframework embeds them instead (see
  // build-dawn.yml's \`-headers\` flag), so "cpp" not containing them there
  // is fine — the xcframework's own headers cover it.
  "cpp",
  "cpp/jsi",
  "cpp/rnwgpu",
  "cpp/rnwgpu/api",
  "cpp/rnwgpu/api/descriptors",
  "cpp/rnwgpu/async",
]

let package = Package(
  name: "react-native-webgpu",
  platforms: [.iOS("15.1"), .macOS("11.0")],
  products: [
    .library(name: "react-native-webgpu", targets: ["react-native-webgpu"])
  ],
  targets: [
    // Dawn's compiled WebGPU implementation. The xcframework embeds the
    // \`webgpu/\` and \`dawn/\` C headers per-slice (built via \`-headers\` in
    // build-dawn.yml), so SPM exposes them to dependents automatically.
    ${renderBinaryTarget(target)},
    .target(
      name: "react-native-webgpu",
      dependencies: ["WebGPUDawn"],
      path: ".",
      sources: ["apple", "cpp/jsi", "cpp/rnwgpu"],
      publicHeadersPath: "apple",
      cSettings: internalHeaderDirs.map { CSetting.headerSearchPath($0) }
        + [.unsafeFlags(follyDefines + cFamilyIncludeFlags)],
      cxxSettings: internalHeaderDirs.map { CXXSetting.headerSearchPath($0) }
        + [.unsafeFlags(follyDefines + cFamilyIncludeFlags)],
      linkerSettings: [
        .linkedFramework("AVFoundation"),
        .linkedFramework("CoreMedia"),
        .linkedFramework("CoreVideo"),
        .linkedFramework("ImageIO"),
      ]
    ),
  ],
  cxxLanguageStandard: .cxx20
)
`;
