import { setMetalApiValidationDisabled } from "../setMetalApiValidation";

// Trimmed-down version of the scheme generated by `npx expo prebuild`.
const makeScheme = (
  launchActionAttributes: string,
) => `<?xml version="1.0" encoding="UTF-8"?>
<Scheme
   LastUpgradeVersion = "1130"
   version = "1.3">
   <BuildAction
      parallelizeBuildables = "YES"
      buildImplicitDependencies = "YES">
   </BuildAction>
   <LaunchAction
      buildConfiguration = "Debug"
      selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
      selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
      launchStyle = "0"
      useCustomWorkingDirectory = "NO"
      ignoresPersistentStateOnLaunch = "NO"
      debugDocumentVersioning = "YES"
      debugServiceExtension = "internal"${launchActionAttributes}
      allowLocationSimulation = "YES">
      <BuildableProductRunnable
         runnableDebuggingMode = "0">
      </BuildableProductRunnable>
   </LaunchAction>
   <ProfileAction
      buildConfiguration = "Release"
      shouldUseLaunchSchemeArgsEnv = "YES">
   </ProfileAction>
</Scheme>
`;

describe("setMetalApiValidationDisabled", () => {
  it("adds enableGPUValidationMode to a scheme without the attribute", () => {
    const result = setMetalApiValidationDisabled(makeScheme(""));
    expect(result).toContain('enableGPUValidationMode = "1"');
    // The attribute must land on the LaunchAction element, not elsewhere.
    const [launchAction] = result.match(/<LaunchAction[^>]*>/)!;
    expect(launchAction).toContain('enableGPUValidationMode = "1"');
  });

  it("overwrites an existing enableGPUValidationMode value", () => {
    const scheme = makeScheme('\n      enableGPUValidationMode = "2"');
    const result = setMetalApiValidationDisabled(scheme);
    expect(result).toContain('enableGPUValidationMode = "1"');
    expect(result).not.toContain('enableGPUValidationMode = "2"');
  });

  it("is idempotent", () => {
    const once = setMetalApiValidationDisabled(makeScheme(""));
    const twice = setMetalApiValidationDisabled(once);
    expect(twice).toBe(once);
  });

  it("produces a valid LaunchAction opening tag", () => {
    const result = setMetalApiValidationDisabled(makeScheme(""));
    const [launchAction] = result.match(/<LaunchAction[^>]*>/)!;
    expect(launchAction.endsWith('enableGPUValidationMode = "1">')).toBe(true);
    expect(launchAction).toContain('allowLocationSimulation = "YES"');
    expect(result.match(/enableGPUValidationMode/g)).toHaveLength(1);
  });

  it("does not touch other actions", () => {
    const result = setMetalApiValidationDisabled(makeScheme(""));
    const [profileAction] = result.match(/<ProfileAction[^>]*>/)!;
    expect(profileAction).not.toContain("enableGPUValidationMode");
  });
});
