// swift-tools-version: 5.9
// Generated by scripts/generate-package-swift.ts — do not edit by hand.
// Re-run that script after a new Dawn release to update the URL/checksum below.
import Foundation
import PackageDescription

// Integration model: React Native 0.87+ native SwiftPM autolinking only.
//
// A dependency shipping its own Package.swift (this one, with
// react-native.config.js pinning its `spm.name`) is picked up as
// "self-managed" and referenced directly, with no CocoaPods involved at all.
// Autolinking references it through a symlink at
// <app>/ios/build/generated/autolinking/libs/react-native-webgpu, and SwiftPM
// resolves this manifest's relative paths against that symlink rather than
// against this package's real location - the same mechanism
// Shopify/react-native-skia's Package.swift documents and uses (PR #4043).
// Because the symlink location is the same for every standard app, the two
// React Native package paths below are constant. React Native's headers and
// the app's generated codegen output arrive as typed SwiftPM products
// (ReactHeaders, ReactNativeHeaders, ReactNativeDependenciesHeaders from the
// generated ReactNative package, ReactAppHeaders from the generated
// React-GeneratedCode package), so no header search paths or unsafeFlags are
// needed anywhere in this manifest.
//
// React Native versions before 0.87 (no native SwiftPM autolinking) can only
// consume react-native-webgpu through the default CocoaPods autolinking - not
// through this Package.swift.

// Absolute location of this package. Used only for the Dawn-version check
// below, which walks real (never symlinked) node_modules sibling paths.
let packageRoot = URL(fileURLWithPath: Context.packageDirectory)
  .resolvingSymlinksInPath().path
let sibling = { (relative: String) -> String in
  URL(fileURLWithPath: "\(packageRoot)/\(relative)").standardized.path
}

// Resolved by SwiftPM itself, lexically, against the symlinked location
// react-native.config.js's `spm.name` pins - NOT computed from
// `packageRoot`/`sibling` above, which point at this package's real,
// non-symlinked location instead. Verified against a real
// `npx react-native spm scaffold` run on 0.87.1: the self-managed symlink
// lands at <app>/ios/build/generated/autolinking/libs/react-native-webgpu,
// and React-GeneratedCode / ReactNative sit at <app>/ios/build/generated/ios
// and <app>/ios/build/xcframeworks respectively - three and four levels up
// from there.
let reactGeneratedCodePath = "../../../ios"
let reactNativeCorePath = "../../../../xcframeworks"

// Skia Graphite and WebGPU must link the exact same Dawn, or the pair links
// fine and crashes at runtime. react-native-skia's podspec enforces this at
// `pod install` time by comparing its libs/.dawn-version against this
// package's `dawn` field. A Swift package has no install hook, so the same
// check runs here, at manifest evaluation. SwiftPM caches evaluations, so
// after changing either package's Dawn version reset the package caches
// (File > Packages > Reset Package Caches) if this does not re-run.
let dawnReleaseTag = "dawn-chrome-m154"
let skiaCandidates = [
  sibling("../@shopify/react-native-skia"), // consumer: sibling in node_modules
  sibling("../../node_modules/@shopify/react-native-skia"), // this monorepo
]
for skia in skiaCandidates {
  // Only Graphite builds of react-native-skia write this marker (Ganesh
  // builds do not link Dawn and impose no constraint).
  guard let data = FileManager.default.contents(atPath: "\(skia)/libs/.dawn-version"),
    let skiaDawn = String(data: data, encoding: .utf8)?
      .trimmingCharacters(in: .whitespacesAndNewlines)
  else { continue }
  if skiaDawn != dawnReleaseTag {
    fatalError(
      """
      react-native-webgpu: Dawn version mismatch. This package links \(dawnReleaseTag) \
      but the @shopify/react-native-skia Graphite build at \(skia) links \(skiaDawn). \
      Align the two packages so the app contains exactly one Dawn.
      """)
  }
  break
}

let follyDefines: [(name: String, value: String?)] = [
  ("FOLLY_NO_CONFIG", nil),
  ("FOLLY_MOBILE", "1"),
  ("FOLLY_USE_LIBCPP", "1"),
  ("FOLLY_CFG_NO_COROUTINES", "1"),
  ("FOLLY_HAVE_CLOCK_GETTIME", "1"),
]

// Unlike a native Xcode target, SwiftPM doesn't generate an implicit
// per-target header map, so quoted includes only resolve within the
// including file's own directory. The sources use bare cross-directory
// includes (e.g. apple/WebGPUModule.h includes "RNWebGPUManager.h" from
// cpp/rnwgpu), so every directory that's the target of one of those bare
// includes has to be listed explicitly here.
let internalHeaderDirs = [
  "apple",
  // "cpp" itself resolves the "webgpu/..." and "dawn/..." namespaced
  // includes. Those two directories are only present locally when built via
  // `yarn install-dawn` (without the xcframework's embedded headers); a
  // remote binaryTarget's xcframework embeds them instead (see
  // build-dawn.yml's `-headers` flag), so "cpp" not containing them there
  // is fine — the xcframework's own headers cover it.
  "cpp",
  "cpp/jsi",
  "cpp/rnwgpu",
  "cpp/rnwgpu/api",
  "cpp/rnwgpu/api/descriptors",
  "cpp/rnwgpu/async",
]

let package = Package(
  name: "react-native-webgpu",
  platforms: [.iOS("15.1"), .macOS("11.0")],
  products: [
    .library(name: "react-native-webgpu", targets: ["react-native-webgpu"]),
    // Exposes the Dawn binaryTarget as its own product so a sibling package
    // (e.g. a future react-native-skia Graphite SPM manifest) can depend on
    // this package's Dawn build directly instead of vendoring a second copy.
    .library(name: "WebGPUDawn", targets: ["WebGPUDawn"]),
  ],
  dependencies: [
    .package(name: "React-GeneratedCode", path: reactGeneratedCodePath),
    .package(name: "ReactNative", path: reactNativeCorePath),
  ],
  targets: [
    // Dawn's compiled WebGPU implementation. The xcframework embeds the
    // `webgpu/` and `dawn/` C headers per-slice (built via `-headers` in
    // build-dawn.yml), so SPM exposes them to dependents automatically.
    .binaryTarget(
      name: "WebGPUDawn",
      url: "https://github.com/wcandillon/react-native-webgpu/releases/download/dawn-chrome-m154/dawn-apple-dawn-chrome-m154.xcframework.zip",
      checksum: "896575ffbc99610198a83d061f8c5a2789139b7f16c669fbf3a9f7a7ac9be123"
    ),
    .target(
      name: "react-native-webgpu",
      dependencies: [
        "WebGPUDawn",
        .product(name: "ReactHeaders", package: "ReactNative"),
        .product(name: "ReactNativeHeaders", package: "ReactNative"),
        .product(name: "ReactNativeDependenciesHeaders", package: "ReactNative"),
        .product(name: "ReactAppHeaders", package: "React-GeneratedCode"),
      ],
      path: ".",
      sources: ["apple", "cpp/jsi", "cpp/rnwgpu"],
      publicHeadersPath: "apple",
      cSettings: internalHeaderDirs.map { CSetting.headerSearchPath($0) }
        + follyDefines.map { CSetting.define($0.name, to: $0.value) },
      cxxSettings: internalHeaderDirs.map { CXXSetting.headerSearchPath($0) }
        + follyDefines.map { CXXSetting.define($0.name, to: $0.value) }
        + [
          // CocoaPods forces both project-wide; native autolinking defines
          // neither. Cheap insurance against a silent -getTurboModule: drop
          // (react-native-skia#4043 hit exactly this) - still verify with a
          // runtime smoke test, not just a clean build, since that failure
          // mode compiles fine and only breaks at runtime.
          .define("RCT_NEW_ARCH_ENABLED", to: "1"),
          .define("RCT_REMOVE_LEGACY_ARCH", to: "1"),
        ],
      linkerSettings: [
        .linkedFramework("AVFoundation"),
        .linkedFramework("CoreMedia"),
        .linkedFramework("CoreVideo"),
        .linkedFramework("ImageIO"),
      ]
    ),
  ],
  cxxLanguageStandard: .cxx20
)
