// swift-tools-version: 5.9
// Generated by scripts/generate-package-swift.ts — do not edit by hand.
// Re-run that script after a new Dawn release to update the URL/checksum below.
import Foundation
import PackageDescription

// Integration model: a local Swift package next to a CocoaPods install.
//
// This manifest targets React Native 0.81+ (the package's peer range), where
// React Native's own headers and the RNWgpuViewSpec codegen output only exist
// inside the consuming app's CocoaPods install. Add this package as a local
// Swift Package dependency in place of the react-native-webgpu pod (export
// RNWGPU_USE_SPM=1 for `pod install`) and keep running `pod install` for
// everything else. The header search paths below point into that Pods
// directory. They can only be expressed as `unsafeFlags`, and SwiftPM rejects
// unsafeFlags in anything but a path dependency, so this package can only be
// consumed locally, never by URL and version.
//
// React Native 0.87 added SwiftPM autolinking. There, a dependency shipping
// its own Package.swift is treated as self-managed and referenced directly,
// and it consumes React Native's headers as SwiftPM products (ReactHeaders,
// ReactNativeHeaders, ReactNativeDependenciesHeaders, plus ReactAppHeaders
// from the app's generated codegen package) with no CocoaPods at all. This
// manifest does not implement that model yet: on a 0.87+ app that has opted
// into SwiftPM autolinking it is picked up as self-managed but cannot find
// React Native's headers. Keep CocoaPods for React Native on those apps.

// Absolute location of this package. Xcode may hand over a symlink (React
// Native 0.87's autolinker does), so resolve it before deriving sibling paths.
let packageRoot = URL(fileURLWithPath: Context.packageDirectory)
  .resolvingSymlinksInPath().path
let sibling = { (relative: String) -> String in
  URL(fileURLWithPath: "\(packageRoot)/\(relative)").standardized.path
}

// Where the consuming app's Pods live. PODS_ROOT is exported by Xcode.app for
// a real build, but never by plain `xcodebuild`, and never while Xcode indexes
// the manifest before a first build. SwiftPM also caches manifest evaluations,
// so an evaluation that ran without it would otherwise be cached with an empty
// include list and surface later as header-not-found errors. Fall back to
// where Pods sit relative to this package for every standard app layout, so
// the result is the same with or without the environment variable.
let podsRootCandidates = [
  sibling("../../ios/Pods"), // consumer: <app>/node_modules/react-native-webgpu
  sibling("../../apps/spm-example/ios/Pods"), // this monorepo
]
let podsRoot =
  ProcessInfo.processInfo.environment["PODS_ROOT"]
  ?? podsRootCandidates.first { FileManager.default.fileExists(atPath: $0) }
  ?? podsRootCandidates[0]

// Skia Graphite and WebGPU must link the exact same Dawn, or the pair links
// fine and crashes at runtime. react-native-skia's podspec enforces this at
// `pod install` time by comparing its libs/.dawn-version against this
// package's `dawn` field. A Swift package has no install hook, so the same
// check runs here, at manifest evaluation. SwiftPM caches evaluations, so
// after changing either package's Dawn version reset the package caches
// (File > Packages > Reset Package Caches) if this does not re-run.
let dawnReleaseTag = "dawn-chrome-m154"
let skiaCandidates = [
  sibling("../@shopify/react-native-skia"), // consumer: sibling in node_modules
  sibling("../../node_modules/@shopify/react-native-skia"), // this monorepo
]
for skia in skiaCandidates {
  // Only Graphite builds of react-native-skia write this marker (Ganesh
  // builds do not link Dawn and impose no constraint).
  guard let data = FileManager.default.contents(atPath: "\(skia)/libs/.dawn-version"),
    let skiaDawn = String(data: data, encoding: .utf8)?
      .trimmingCharacters(in: .whitespacesAndNewlines)
  else { continue }
  if skiaDawn != dawnReleaseTag {
    fatalError(
      """
      react-native-webgpu: Dawn version mismatch. This package links \(dawnReleaseTag) \
      but the @shopify/react-native-skia Graphite build at \(skia) links \(skiaDawn). \
      Align the two packages so the app contains exactly one Dawn.
      """)
  }
  break
}

// Static-library Pods layout. With `use_frameworks!` CocoaPods keeps headers
// inside each framework instead and none of these paths exist; the podspec
// refuses RNWGPU_USE_SPM in that mode.
let publicHeaders = "\(podsRoot)/Headers/Public"
let privateHeaders = "\(podsRoot)/Headers/Private"
let headerSearchPaths = [
  publicHeaders,
  // Yoga's headers are CocoaPods-private (apps aren't meant to use Yoga's
  // C++ API directly), but React-Fabric's view props headers include them
  // transitively.
  "\(privateHeaders)/Yoga",
  "\(publicHeaders)/React-Core",
  "\(publicHeaders)/React-jsi",
  "\(publicHeaders)/React-callinvoker",
  "\(publicHeaders)/React-NativeModulesApple",
  "\(publicHeaders)/React-RCTFabric",
  "\(publicHeaders)/ReactCodegen",
  "\(publicHeaders)/RCT-Folly",
  "\(publicHeaders)/RCTRequired",
  "\(publicHeaders)/RCTTypeSafety",
  "\(publicHeaders)/FBLazyVector",
  "\(publicHeaders)/ReactCommon",
  "\(publicHeaders)/React-Fabric",
  "\(publicHeaders)/React-graphics",
  "\(publicHeaders)/React-utils",
  "\(publicHeaders)/React-featureflags",
  "\(publicHeaders)/React-rendererdebug",
  "\(publicHeaders)/React-debug",
  "\(publicHeaders)/React-timing",
  "\(publicHeaders)/React-runtimescheduler",
  "\(publicHeaders)/React-rendererconsistency",
  "\(publicHeaders)/React-performancetimeline",
  "\(publicHeaders)/React-runtimeexecutor",
  "\(publicHeaders)/React-cxxreact",
  "\(publicHeaders)/hermes-engine",
  "\(publicHeaders)/glog",
  "\(publicHeaders)/DoubleConversion",
  "\(publicHeaders)/fmt",
  "\(publicHeaders)/fast_float",
]
// The only unsafe flags left: .headerSearchPath cannot escape the target
// path, and these live in the app's Pods directory.
let cFamilyIncludeFlags = headerSearchPaths.map { "-I\($0)" }
let follyDefines: [(name: String, value: String?)] = [
  ("FOLLY_NO_CONFIG", nil),
  ("FOLLY_MOBILE", "1"),
  ("FOLLY_USE_LIBCPP", "1"),
  ("FOLLY_CFG_NO_COROUTINES", "1"),
  ("FOLLY_HAVE_CLOCK_GETTIME", "1"),
]

// Unlike a native Xcode target, SwiftPM doesn't generate an implicit
// per-target header map, so quoted includes only resolve within the
// including file's own directory. The sources use bare cross-directory
// includes (e.g. apple/WebGPUModule.h includes "RNWebGPUManager.h" from
// cpp/rnwgpu), so every directory that's the target of one of those bare
// includes has to be listed explicitly here.
let internalHeaderDirs = [
  "apple",
  // "cpp" itself resolves the "webgpu/..." and "dawn/..." namespaced
  // includes. Those two directories are only present locally when built via
  // `yarn install-dawn` (without the xcframework's embedded headers); a
  // remote binaryTarget's xcframework embeds them instead (see
  // build-dawn.yml's `-headers` flag), so "cpp" not containing them there
  // is fine — the xcframework's own headers cover it.
  "cpp",
  "cpp/jsi",
  "cpp/rnwgpu",
  "cpp/rnwgpu/api",
  "cpp/rnwgpu/api/descriptors",
  "cpp/rnwgpu/async",
]

let package = Package(
  name: "react-native-webgpu",
  platforms: [.iOS("15.1"), .macOS("11.0")],
  products: [
    .library(name: "react-native-webgpu", targets: ["react-native-webgpu"])
  ],
  targets: [
    // Dawn's compiled WebGPU implementation. The xcframework embeds the
    // `webgpu/` and `dawn/` C headers per-slice (built via `-headers` in
    // build-dawn.yml), so SPM exposes them to dependents automatically.
    .binaryTarget(
      name: "WebGPUDawn",
      url: "https://github.com/wcandillon/react-native-webgpu/releases/download/dawn-chrome-m154/dawn-apple-dawn-chrome-m154.xcframework.zip",
      checksum: "896575ffbc99610198a83d061f8c5a2789139b7f16c669fbf3a9f7a7ac9be123"
    ),
    .target(
      name: "react-native-webgpu",
      dependencies: ["WebGPUDawn"],
      path: ".",
      sources: ["apple", "cpp/jsi", "cpp/rnwgpu"],
      publicHeadersPath: "apple",
      cSettings: internalHeaderDirs.map { CSetting.headerSearchPath($0) }
        + follyDefines.map { CSetting.define($0.name, to: $0.value) }
        + [.unsafeFlags(cFamilyIncludeFlags)],
      cxxSettings: internalHeaderDirs.map { CXXSetting.headerSearchPath($0) }
        + follyDefines.map { CXXSetting.define($0.name, to: $0.value) }
        + [.unsafeFlags(cFamilyIncludeFlags)],
      linkerSettings: [
        .linkedFramework("AVFoundation"),
        .linkedFramework("CoreMedia"),
        .linkedFramework("CoreVideo"),
        .linkedFramework("ImageIO"),
      ]
    ),
  ],
  cxxLanguageStandard: .cxx20
)
