name: iOS build
on:
  pull_request:
    paths:
      - 'package/ios/**'
      - 'package/cpp/**'
      - 'example/package.json'
      - '.github/workflows/**'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        working-directory: [example]
    concurrency:
      group: ios-example-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: package/yarn.lock

      - name: Install Package
        run: cd package; yarn install --frozen-lockfile

      - name: Install Example
        run: cd ${{ matrix.working-directory }}; yarn install --frozen-lockfile

      - name: Download Dawn Binary Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "build-dawn.yml"
          repo: wcandillon/react-native-webgpu
          github_token: ${{secrets.GITHUB_TOKEN}}
          path: artifacts
          branch: main
          name: dawn-libs

      - name: Copy Artifacts to libs folder
        working-directory: package
        run: yarn copy-artifacts

      - name: Restore Pods from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.working-directory }}/ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}

      - name: Install Pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: pod install

      - name: Check if Podfile.lock has changed
        working-directory: ${{ matrix.working-directory }}/ios
        run: |
          # Use git diff to get differences, excluding lines for 'COCOAPODS:' and filtering out 'React-RCTAppDelegate:'
          # Right now we also exclude changes to React-RCTAppDelegate because of
          # https://github.com/facebook/react-native/issues/39971
          if git diff --ignore-all-space -I 'COCOAPODS:' -I "React-RCTAppDelegate" HEAD -- example/ios/Podfile.lock | grep -q .; then
              echo "Podfile.lock has local changes, please update it."
              # Display diff, but exclude 'React-RCTAppDelegate:' changes for clarity
              git diff --ignore-all-space -I 'COCOAPODS:' -I "React-RCTAppDelegate" HEAD -- example/ios/Podfile.lock | grep -q .;
              exit 1
          else
              echo "Podfile.lock is up to date."
          fi

      - name: Restore build artifacts from cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-ios-derived-data-${{ hashFiles(format('{0}/ios/Podfile.lock', matrix.working-directory)) }}
  
      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: CI=true yarn ios --simulator 'iPhone 14 Pro'

      # - name: Run e2e tests
      #   working-directory: package
      #   run: yarn e2e

      # - name: Start package manager
      #   working-directory: example
      #   run: E2E=true yarn start &

      # - name: Take screenshot
      #   run: xcrun simctl io booted screenshot screenshot.png
        
      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: screenshot.png
      #     name: Download-screenshots
