name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:
    inputs:
      build_android:
        description: 'Build for Android'
        type: boolean
        default: false
      build_ios:
        description: 'Build for iOS'
        type: boolean
        default: false
      build_macos:
        description: 'Build for macOS'
        type: boolean
        default: false
      run_reference_tests:
        description: 'Run reference tests'
        type: boolean
        default: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clang Format
        working-directory: packages/webgpu
        run: yarn clang-format

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn tsc

      - name: Build
        working-directory: packages/webgpu
        run: yarn build

      - name: Package
        working-directory: packages/webgpu
        run: yarn pack

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: packages/webgpu/package.tgz
          compression-level: 0

  reference-tests:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.run_reference_tests == 'true'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Chrome
        run: npx puppeteer browsers install chrome

      - name: Run reference test suite
        working-directory: packages/webgpu
        run: yarn test:ref

  build-android:
    runs-on: self-hosted
    env:
      TURBO_CACHE_DIR: .turbo/android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache turborepo for Android
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-android-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-android

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('./apps/example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android SDK
        run: echo "sdk.dir=$ANDROID_HOME" > $GITHUB_WORKSPACE/apps/example/android/local.properties

      - name: Build example for Android
        env:
          JAVA_OPTS: "-XX:MaxHeapSize=6g"
        run: |
          yarn turbo run build:android --concurrency 1

      - name: Cache apk
        uses: actions/cache/save@v4
        env:
          cache-name: cache-apk
        with:
          path: apps/example/android/app/build/outputs/apk/debug/app-debug.apk
          key: apk-${{ github.sha }}

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-example-apk
          path: apps/example/android/app/build/outputs/apk/debug/app-debug.apk

  test-android:
    needs: build-android
    runs-on: self-hosted
    timeout-minutes: 60
    env:
      TURBO_CACHE_DIR: .turbo/android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Restore APK
        id: cache-apk
        uses: actions/cache/restore@v4
        with:
          path: apps/example/android/app/build/outputs/apk/debug/app-debug.apk
          key: apk-${{ github.sha }}

      - name: Start Package Manager
        working-directory: apps/example
        run: E2E=true yarn start &

      - name: Run Android Emulator Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 5X
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swangle_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            # Wait for Metro bundler
            sleep 10

            # Install and launch app
            adb install -r apps/example/android/app/build/outputs/apk/debug/app-debug.apk
            adb shell monkey -p com.microsoft.reacttestapp 1

            # Run tests
            cd packages/webgpu && CI=true yarn test

      - name: Upload test snapshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: packages/webgpu/src/__tests__/snapshots/
          name: tests-snapshots-android

  build-test-ios:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_ios == 'true'
    runs-on: self-hosted
    env:
      TURBO_CACHE_DIR: .turbo/ios
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache turborepo for iOS
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-ios-

      - name: Check turborepo cache for iOS
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Install CocoaPods
        working-directory: apps/example/ios
        run: pod install

      - name: Start Package Manager
        working-directory: apps/example
        run: E2E=true yarn start &

      - name: Build example for iOS
        working-directory: apps/example
        run: yarn ios --simulator 'iPhone 16 Pro'

      - name: Run e2e tests
        working-directory: packages/webgpu
        run: CI=true E2E=true yarn test

      - name: Upload test snapshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: packages/webgpu/src/__tests__/snapshots/
          name: tests-snapshots-ios

  build-macos:
    runs-on: self-hosted
    env:
      TURBO_CACHE_DIR: .turbo/macos
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache turborepo for macOS
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-macos-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-macos-

      - name: Check turborepo cache for macOS
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:macos --cache-dir="${{ env.TURBO_CACHE_DIR }}" --dry=json)).tasks.find(t => t.task === 'build:macos').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Build example for macOS
        run: |
          yarn turbo run build:macos --cache-dir="${{ env.TURBO_CACHE_DIR }}"
